export const Statearr = [
  { id: "AP", name: "Andhra Pradesh", img: "images/AP.jpg" },
  { id: "AR", name: "Arunachal Pradesh", img: "images/AR.jpg" },
  { id: "AS", name: "Assam", img: "images/AS.jpg" },
  { id: "BR", name: "Bihar", img: "images/BR.png" },
  { id: "CT", name: "Chhattisgarh", img: "" },
  { id: "GA", name: "Goa", img: "images/GA.png" },
  { id: "GJ", name: "Gujarat", img: "images/GJ.png" },
  { id: "HR", name: "Haryana", img: "images/HR.png" },
  { id: "HP", name: "Himachal Pradesh", img: "images/HP.png" },
  { id: "JH", name: "Jharkhand", img: "images/JH.png" },
  { id: "KA", name: "Karnataka", img: "images/KA.png" },
  { id: "KL", name: "Kerala", img: "images/KL.png" },
  { id: "MP", name: "Madhya Pradesh", img: "images/MP.png" },
  { id: "MH", name: "Maharashtra", img: "images/MH.png" },
  { id: "MN", name: "Manipur", img: "images/MN.png" },
  { id: "ML", name: "Meghalaya", img: "images/ML.png" },
  { id: "MZ", name: "Mizoram", img: "" },
  { id: "NL", name: "Nagaland", img: "" },
  { id: "OR", name: "Odisha", img: "" },
  { id: "PB", name: "Punjab", img: "" },
  { id: "RJ", name: "Rajasthan", img: "" },
  { id: "SK", name: "Sikkim", img: "" },
  { id: "TN", name: "Tamil Nadu", img: "" },
  { id: "TG", name: "Telangana", img: "" },
  { id: "TR", name: "Tripura", img: "" },
  { id: "UP", name: "Uttar Pradesh", img: "" },
  { id: "UK", name: "Uttarakhand", img: "" },
  { id: "WB", name: "West Bengal", img: "images/WB.jpg" },
  { id: "AN", name: "Andaman and Nicobar Islands", img: "" },
  { id: "CH", name: "Chandigarh", img: "" },
  { id: "DN", name: "Dadra and Nagar Haveli and Daman and Diu", img: "" },
  { id: "DL", name: "Delhi", img: "" },
  { id: "JK", name: "Jammu and Kashmir", img: "" },
  { id: "LD", name: "Lakshadweep", img: "" },
  { id: "PY", name: "Puducherry", img: "" }
];
