export const Statearr = [
  { id: "AP", name: "Andhra Pradesh", img: "images/AP.jpg" },
  { id: "AR", name: "Arunachal Pradesh", img: "images/AR.jpg" },
  { id: "AS", name: "Assam", img: "images/AS.jpg" },
  { id: "BR", name: "Bihar", img: "images/BR.png" },
  { id: "CT", name: "Chhattisgarh", img: "images/CT.png" },
  { id: "GA", name: "Goa", img: "images/GA.png" },
  { id: "GJ", name: "Gujarat", img: "images/GJ.png" },
  { id: "HR", name: "Haryana", img: "images/HR.png" },
  { id: "HP", name: "Himachal Pradesh", img: "images/HP.png" },
  { id: "JH", name: "Jharkhand", img: "images/JH.png" },
  { id: "KA", name: "Karnataka", img: "images/KA.png" },
  { id: "KL", name: "Kerala", img: "images/KL.png" },
  { id: "MP", name: "Madhya Pradesh", img: "images/MP.png" },
  { id: "MH", name: "Maharashtra", img: "images/MH.png" },
  { id: "MN", name: "Manipur", img: "images/MN.png" },
  { id: "ML", name: "Meghalaya", img: "images/ML.png" },
  { id: "MZ", name: "Mizoram", img: "images/MZ.png" },
  { id: "NL", name: "Nagaland", img: "images/NL.png" },
  { id: "OR", name: "Odisha", img: "images/OR.png" },
  { id: "PB", name: "Punjab", img: "images/PB.png" },
  { id: "RJ", name: "Rajasthan", img: "images/RJ.png" },
  { id: "SK", name: "Sikkim", img: "images/SK.png" },
  { id: "TN", name: "Tamil Nadu", img: "images/TN.png" },
  { id: "TG", name: "Telangana", img: "images/TG.png" },
  { id: "TR", name: "Tripura", img: "images/TR.png" },
  { id: "UP", name: "Uttar Pradesh", img: "images/UP.png" },
  { id: "UK", name: "Uttaranchal", img: "images/UK.png" },
  { id: "WB", name: "West Bengal", img: "images/WB.jpg" },
  { id: "AN", name: "Andaman and Nicobar Islands", img: "images/AN.png" },
  { id: "CH", name: "Chandigarh", img: "images/CH.png" },
  { id: "DN", name: "Dadra and Nagar Haveli and Daman and Diu", img: "images/DN.png" },
  { id: "DL", name: "Delhi", img: "images/DL.png" },
  { id: "JK", name: "Jammu and Kashmir", img: "images/JK.png" },
  { id: "LD", name: "Lakshadweep", img: "images/LD.png" },
  { id: "PY", name: "Puducherry", img: "images/PY.png" },
  { id: "LA", name: "Ladakh", img: "images/LA.png" }
];
